### ISSUE TITLE
Why is LAYER_ARRAY_BUFFER_SIZE set to 65536 in wavenet.cpp? 

### ISSUE THREAD

**Issue by postcode-x** [sdatkinson/NeuralAmpModelerCore#135]
I am trying to run this code on the Daisy Seed platform, which has limited memory, and I observe significant memory usage spikes during the instantiation of _layer_buffers. Is this specific number  tied to a specific requirement for the Wavenet model's performance or functionality?

**Comment by sdatkinson** [comment]
Nah. The thinking when I first wrote that was that I'd rather not have to copy the end of the buffer back to the start too often, and I was thinking about general-purpose computers where memory is cheap.

However, the cost of that memcpy is probably vanishingly small compared to the rest of what's going on.

I forget the full context since I'm not looking at it, but I thought I had a few comments about it. There _is_ a lower length limit, but this isn't close to it.

You should be able to shorten it a lot without any consequences.

But also, the allocations there shouldn't be in a time-critical part of the code. They are right now, and it's just a to-do to clean that up (i.e. do all the memory allocations during `Reset()`.)

hope that helps!
