### ISSUE TITLE
Apply "anti-pop" for all network types

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerCore#61]
The WaveNet implementation has some "anti-pop" code for handling discontinuities in the audio stream when switching models. The other network types could benefit from this as well. Perhaps it could be moved into the underlying dsp code?

I'm happy to make the required code changes.

**Comment by sdatkinson** [comment]
ConvNet would benefit from it, but the LSTM shouldn't need it--i get the "steady-state" hidden state while expecting the model and initialize those parameters to those values when initializing the model, so it shouldn't need it.

(Anti-popping for the DC offset is another matter and a valid reason for it).

Does that ring true with what you see?

I ask because (1) hopefully it's working like I described it and (2) if so, it'd be cool if it only had to be a handful of samples long for the LSTM.

**Comment by mikeoliphant** [comment]
So, there are actually *two* sources of pop issues. First is any initial instability in the model. The second is the discontinuity in the audio signal caused when switching models. WaveNet suffers from both (with the initial instability solved with the current anti-pop). I guess LSTM only suffers from the second (I wondered why the initial state was being stored - that explains it).

Now that I've thought about it some more, I guess the discontinuity issue can't really be solved in the NAM code, since it doesn't know what the previous output signal was before switching models.

**Comment by mikeoliphant** [comment]
@sdatkinson Can you clarify why the WaveNet models are unstable initially and need the anti-pop? I would have thought they would be deterministic based on the receptive field since there is no feedback connection?

Is there a way to initialize the WaveNet processing efficiently (either assuming zeros as past receptive field, or using actual sample history)?

Failing that, pre-running the model for a decent number of samples after loading it also eliminates the instability without the need for the "anti-pop" code, and has the benefit that it can be done outside of the processing loop (see PR https://github.com/mikeoliphant/neural-amp-modeler-lv2/pull/46 on the LV2 repo).

**Comment by sdatkinson** [comment]
> Is there a way to initialize the WaveNet processing efficiently (either assuming zeros as past receptive field, or using actual sample history)?

Yep, that would work.

> Failing that, pre-running the model for a decent number of samples after loading it also eliminates the instability without the need for the "anti-pop" code, and has the benefit that it can be done outside of the processing loop (see PR https://github.com/mikeoliphant/neural-amp-modeler-lv2/pull/46 from @falkTX on the LV2 repo).

Yep, that would work as well 🙂 (this is what the LSTM does [when exporting](https://github.com/sdatkinson/neural-amp-modeler/blob/06547c8579cbec9f0eb4f8ca732083e91b672e4e/nam/models/recurrent.py#L330C26-L330C26)--the resulting hidden & cell states are saved as part of the parameters). One could do the same with the WaveNet and ConvNet--I just never got around to it.

**Comment by sdatkinson** [comment]
The reason why the WaveNet "pops" is because the steady-state values in between the convolutions for a constant zero input aren't necessarily zero, but that's what they're initialized to.

Once it runs for a length of time equal to the receptive field of the model, it'll be good.

**Comment by mikeoliphant** [comment]
> Once it runs for a length of time equal to the receptive field of the model, it'll be good.

The ideal solution would be if a new model could be initialized at processing time using the most recent "receptive field" samples (rather than zero input). This would minimize discontinuities (the little micro-pop you get even after doing anti-pop) in the audio if the model is switched while audio is active.

That probably isn't practical, though, if it requires full processing of the model over the number of samples in the receptive field - it would create too much of a real-time processing spike.

**Comment by mikeoliphant** [comment]
For now, though, it seems like a win to switch from using anti-pop for WaveNet to initializing the model with zero input over the receptive field when the model is created. It would remove the (admittedly minimal) real-time overhead of the anti-pop pass, as well as the fade-in transition.

**Comment by mikeoliphant** [comment]
PR https://github.com/sdatkinson/NeuralAmpModelerCore/pull/71 submitted to switch from anti-pop to pre-warming on creation.

**Comment by sdatkinson** [comment]
Just commented on #71.

Coming back to this, I think that the solution I'd prefer is that it does seem reasonable to have a _separate_ anti-pop DSP module. It could live in `dsp/anti_pop.h`.

The semantics could be the following:

* Upon loading a new model, one calls `antiPop.reset(namModel->get_receptive_field()`.
* During processing, `void AntiPop::process(sample** outputBuffer, const size_t numFrames)` would apply the anti-pop in-place.

This slims the interface between anti-pop and the NAM model to the model needing to know about its receptive field (or even to define some other getter since e.g. LSTM's "receptive field" is a little unclear depending on how you'd define it maybe `get_pop_length()` that descries how long it usually lasts for the model, and LSTMs could fudge it and say like 4096 and be good).

It also gives the choice of solving the problem this way, or by "warmup" --the library can avoid being opinionated either way since there are trade-offs for each approach and it's not necessary to impose one solution on folks.

Let me know what you think about this. If it sounds good, we can (1) change this Issue to "Implement anti-pop module" (and lmk if you want to tackle it or I can), and (2) put another Issue for the required getter from the DSP class.

**Comment by mikeoliphant** [comment]
> LSTMs could fudge it and say like 4096 and be good

LSTM doesn't need it at all, correct? The models have pre-stabilized weights. Or are you thinking about parameterized models again?

> It also gives the choice of solving the problem this way, or by "warmup" --the library can avoid being opinionated either way since there are trade-offs for each approach and it's not necessary to impose one solution on folks.

That would be a better solution for me than having anti-pop always on, but my worry is that it complicates things for the average person trying to implement NAM into their framework.

What if we did the following:

- Break out anti-pop into a separate operation as you suggest
- Add a **warm_up()** method to NAM models that does model-appropriate warm-up behavior (LSTM could just do nothing)
- Add an option to **get_dsp()** to apply warm-up (on by default would be my preference)

**Comment by sdatkinson** [comment]
Thanks for your patience; I've been thinking about this and haven't had a moment to get back to it.

> LSTM doesn't need it at all, correct? The models have pre-stabilized weights. 

I was thinking of the "second type" of discontinuity you mentioned on [July 6](https://github.com/sdatkinson/NeuralAmpModelerCore/issues/61#issuecomment-1623815364)--due to the input signal being suddenly nonzero.

> my worry is that it complicates things for the average person trying to implement NAM into their framework.

It's a fair point.

Here's a way out: let's get on with developing for v0.1 and make some breaking changes. For one, I think I'm going to remove the parametric models from the repo altogether. The design would be that one could easily define classes that extend those in this repo to have that functionality, but this would stop trying to do both at the same time. But by focusing on the "snapshot" use case, this whole repo might be simplified quite a bit overall for most people by making other breaking changes at the same time (e.g. removing the non-NAM dsp code as well).

Under those terms, I could even do you one better and get rid of the third bullet (add an option) and just always do it 🙂 Does that sound like a good resolution?

All I'd ask under that case is to give me a little bit of time to do some of that refactoring. We could merge the #71 into a `v0.1` branch and get to work there.

The tradeoff would be that if you want it sooner, your choices would be to either (A) work off a fork for a while with that "in between" API, or (B) work off the (probably will be quite unstable) `v0.1` dev branch as I go through breaking things and clearing out the cruft until it gets clean enough for me to merge it back onto `main` and finish the work for v0.1 there.

But either way, it seems to me that the key is dropping a stake in the ground for v0.0.1 and moving on.

**Comment by mikeoliphant** [comment]
> I was thinking of the "second type" of discontinuity you mentioned on [July 6](https://github.com/sdatkinson/NeuralAmpModelerCore/issues/61#issuecomment-1623815364)--due to the input signal being suddenly nonzero.

I've been thinking about and experimenting with this a bit lately, and handling all of the potential causes for discontinuities is pretty tough. You have discontinuity if a new model stabilized on zero input gets switched to with non-zero input. Even if a new model is pre-warmed with current receptive field input, you'll get discontinuities if it has phase or volume differences from the old model (which is probably more the rule rather than the exception).

The only way, I think, to *guarantee* a clean transition is to pre-warm the new model and then crossfade from old to new - which requires both models to be run at the same time during real-time processing. Maybe something to consider as an option, but it isn't practical under resource-limited operation.

**Comment by mikeoliphant** [comment]
> But either way, it seems to me that the key is dropping a stake in the ground for v0.0.1 and moving on.

That sounds like a great plan to me!

My lv2 repo has always been pointed at a fork of the core so that I can use changes before they get merged upstream, so I'm ok with a delay.

I think removing the parametric stuff for now is a good idea - it complicates things, and we don't have any *real* use cases right now. Better to re-add it later if/when it becomes an active development area.
