### ISSUE TITLE
Change dsp to nam?

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerCore#88]
It might make sense to rename dsp.cpp/.h to nam.cpp/.h and also rename the DSP class.

**Comment by sdatkinson** [comment]
Mmh, I disagree. The reason I'm thinking of is that I intend to extend the DSP class for the resampling functionality for the iPlug2 plugin, and I'd like for the resampler to have the same interface as the current NAM models so that the RTL can use the same interface whether the model needs resampling or not.

But in terms of naming, the point is that the DSP class isn't itself inherently "neural", and that's on purpose (I don't really like making that distinction in general).

Lmk if you think I'm missing something or else feel free to close.

**Comment by mikeoliphant** [comment]
I agree with you for the AudioDSPTools stuff - I'm assuming the DSP class framework there probably came from iPlug2? And I'd assume that resampling would go in the AudioDSPTools repo?

The NAM DSP class in this repo is a different interface, though, and the dsp.h/dsp.cpp code and interface here are pretty specific to NAM.

**Comment by sdatkinson** [comment]
> I'm assuming the DSP class framework there probably came from iPlug2?

Actually, it might have been a second attempt to define the interface that I was going to later back-port to the NAM class interface.

I forget though, and  I'm pretty happy with the `void process(float*, float*, int)` signature. That's the bit that I'm expecting the resampler to conform to.

So I'm just going to put it in the `NeuralAmpModelerPlugin` repo first since that'd be the more conservative choice. If I like it after trying it on and want to use it in other places then I'll move it out somewhere. 

---

I think I'm not quite convinced right now, so I'm going to close this just to make a decision and not leave it dangling. But I'm open to revisiting it in the future, so you're welcome to remind me if something else appears as context 🙂
